### ISSUE TITLE
Error: PostCSS plugin postcss-mixins requires PostCSS 8.

### ISSUE THREAD

**Issue by regenrek** [postcss/postcss-mixins#112]
Hi, 

I've added postcss fresh from the npm repo (8.1.1) and postcss-mixins but getting this error.
Working on a fresh vue/nuxt project.

Any ideas?

```

Module build failed (from ./node_modules/postcss-loader/src/index.js):
Error: PostCSS plugin postcss-mixins requires PostCSS 8.
Migration guide for end-users:
https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
    at Processor.normalize (/Users/kevinkernegger/projects/mjpush/node_modules/postcss-loader/node_modules/postcss/lib/processor.js:167:15)
    at new Processor (/Users/kevinkernegger/projects/mjpush/node_modules/postcss-loader/node_modules/postcss/lib/processor.js:56:25)
    at postcss (/Users/kevinkernegger/projects/mjpush/node_modules/postcss-loader/node_modules/postcss/lib/postcss.js:55:10)
    at /Users/kevinkernegger/projects/mjpush/node_modules/postcss-loader/src/index.js:140:12
                                                      friendly-errors 16:22:38
 @ ./node_modules/prismjs/themes/prism.css 4:14-137 14:3-18:5 15:22-145
 @ ./.nuxt/App.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi ./node_modules/@nuxt/components/lib/installComponents.js eventsource-polyfill webpack-hot-middleware/client?reload=true&timeout=30000&ansiColors=&overlayStyles=&path=%2F__webpack_hmr%2Fclient&name=client ./.nuxt/client.js
                                                      friendly-errors 16:22:38

 ERROR  in ./layouts/default.vue?vue&type=style&index=0&lang=css&

Module build failed (from ./node_modules/postcss-loader/src/index.js):
Error: PostCSS plugin postcss-mixins requires PostCSS 8.
Migration guide for end-users:
https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
    at Processor.normalize (/Users/kevinkernegger/projects/mjpush/node_modules/postcss-loader/node_modules/postcss/lib/processor.js:167:15)
    at new Processor (/Users/kevinkernegger/projects/mjpush/node_modules/postcss-loader/node_modules/postcss/lib/processor.js:56:25)
    at postcss (/Users/kevinkernegger/projects/mjpush/node_modules/postcss-loader/node_modules/postcss/lib/postcss.js:55:10)
    at /Users/kevinkernegger/projects/mjpush/node_modules/postcss-loader/src/index.js:140:12
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
                                                      friendly-errors 16:22:38
 @ ./node_modules/vue-style-loader??ref--3-oneOf-1-0!./node_modules/css-loader/dist/cjs.js??ref--3-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--3-oneOf-1-2!./node_modules/@nuxt/components/dist/loader.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./layouts/default.vue?vue&type=style&index=0&lang=css& 4:14-368 14:3-18:5 15:22-376
 @ ./layouts/default.vue?vue&type=style&index=0&lang=css&
 @ ./layouts/default.vue
 @ ./.nuxt/App.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi ./node_modules/@nuxt/components/lib/installComponents.js eventsource-polyfill webpack-hot-middleware/client?reload=true&timeout=30000&ansiColors=&overlayStyles=&path=%2F__webpack_hmr%2Fclient&name=client ./.nuxt/client.js
```

Regards

**Comment by regenrek** [comment]
Ok sorry I've read this unsupported right now https://github.com/nuxt/nuxt.js/issues/8087
