### ISSUE TITLE
Conditionals inside mixins

### ISSUE THREAD

**Issue by Galvo87** [postcss/postcss-mixins#36]
Hi, I was wondering if I can use conditional loops inside mixins, it doesn't matter if in plain css or in js...
I am trying to do this in js, but when compiling I always get this error 'CssSyntaxError' via Webpack... if I remove the various if...else everything is fine, but this would lead to a lot of duplicated code.

**Comment by ai** [comment]
Can you put stacktrace of CssSyntaxError, your webpack config and input CSS.

**Comment by Galvo87** [comment]
Sure, https://gist.github.com/Galvo87/7a2e39da778bde23b972

**Comment by ai** [comment]
Let’s try to clean build process.

There is not sense for `cssnext-loader!postcss-loader`, because cssnext is just few PostCSS plugins. So you can use `postcss-cssnext` in `postcss-loader`.

**Comment by Galvo87** [comment]
Excuse me @ai, what do you mean with "So you can use postcss-cssnext in postcss-loader" ?
I love postcss but I must have the possibility to use imports and mixins to create my own css framework...
Can't think of switching back to scss...

**Comment by ai** [comment]
@Galvo87 right now you use `cssnext-loader` and `postcss-loader`. `postcss-loader` contains PostCSS. And `cssnext-loader` contains PostCSS with `postcss-cssnext` plugin.

So right now you parse CSS twice (in `postcss-loader` and `cssnext-loader`). So you need to remove `cssnext-loader` and add `postcss-cssnext` plugin to `postcss-loader`.

These changes will clean your log to find a error (or even may fix a error, because 2 PostCSS withh different version may produce a error).

**Comment by Galvo87** [comment]
Ok, I loaded css-next as a postcss plugin, this is the error stacktrace

ERROR in ./~/css-loader!./~/postcss-loader!./app/directives/lg-hello.css
Module build failed: TypeError: undefined is not a function
    at cssnextLoader (/Volumes/My World/Development/Projects/webpack-angular/node_modules/cssnext-loader/index.js:21:8)
    at LazyResult.run (/Volumes/My World/Development/Projects/webpack-angular/node_modules/postcss-loader/node_modules/postcss/lib/lazy-result.js:201:20)
    at /Volumes/My World/Development/Projects/webpack-angular/node_modules/postcss-loader/node_modules/postcss/lib/lazy-result.js:115:37
    at LazyResult.asyncTick (/Volumes/My World/Development/Projects/webpack-angular/node_modules/postcss-loader/node_modules/postcss/lib/lazy-result.js:129:15)
    at /Volumes/My World/Development/Projects/webpack-angular/node_modules/postcss-loader/node_modules/postcss/lib/lazy-result.js:127:27
    at LazyResult.asyncTick (/Volumes/My World/Development/Projects/webpack-angular/node_modules/postcss-loader/node_modules/postcss/lib/lazy-result.js:129:15)
    at processing.Promise.then._this2.processed (/Volumes/My World/Development/Projects/webpack-angular/node_modules/postcss-loader/node_modules/postcss/lib/lazy-result.js:155:20)
    at LazyResult.async (/Volumes/My World/Development/Projects/webpack-angular/node_modules/postcss-loader/node_modules/postcss/lib/lazy-result.js:152:27)
    at LazyResult.then (/Volumes/My World/Development/Projects/webpack-angular/node_modules/postcss-loader/node_modules/postcss/lib/lazy-result.js:75:21)
    at Object.module.exports (/Volumes/My World/Development/Projects/webpack-angular/node_modules/postcss-loader/index.js:47:32)
 @ ./app/directives/lg-hello.css 4:14-127

**Comment by ai** [comment]
You still have `cssnext-loader` in stacktrace ;).

Show me your webpack config. (Also use code block for stacktraces.)

**Comment by Galvo87** [comment]
Sure :)

```javascript
var lgMixins = require('./app/mixins');

var path = require('path');
var webpack = require('webpack');
var pMixins = require('postcss-mixins')({
	mixins: lgMixins
});
var simpleVars = require('postcss-simple-vars');
var conditionalFor = require('postcss-for');
var conditionalEach = require("postcss-each");
var conditionalIf = require('postcss-conditionals');
var nested = require('postcss-nested');
var customProperties = require("postcss-custom-properties");
var postcssImport = require('postcss-import');
var cssnext = require('cssnext-loader');
var hexToRgba = require('postcss-color-hex-alpha');
var opacityFix = require('postcss-opacity');
var remToPx = require('pixrem');
var mqPacker = require('css-mqpacker');
var zIndex = require('postcss-zindex');
var clearfix = require('postcss-clearfix');
var easings = require('postcss-easings');
var focus = require('postcss-focus');
var cssReport = require('postcss-reporter');
var cssStats = require('postcss-cssstats');
var removeComments = require('postcss-discard-comments');
var fontPath = require('postcss-fontpath');
var browserSync = require('browser-sync-webpack-plugin');

var config = {
	context: __dirname + '/app',
	entry: './index.js',
	output: {
		path: __dirname + '/app',
		filename: 'bundle.js'
	},
	// Setting up plugins
	plugins: [
		new webpack.DefinePlugin({
			ON_TEST: process.env.NODE_ENV === 'test'
		}),
		// BrowserSync options
		new browserSync({
			// Serving to http://localhost:3000
			host: 'localhost',
			port: 3000,
			// proxy the Webpack Dev Server endpoint through BrowserSync
			proxy: 'http://localhost:8080/'
		}, {
			// Should BrowserSync or Webpack Dev Server reload the page?
			reload: true
		})
	],
	// Instructing weboack how to handle different file formats
	module: {
		preloaders: [
			// Linting js with eslint
			{
				test: /\.js$/,
				loader: 'eslint-loader',
				exclude: /node_modules/
			}
		],
		loaders: [
			// Transpiling js with Babel
			{
				test: /\.js$/,
				loader: 'ng-annotate!babel-loader',
				exclude: /node_modules/
			},
			// Extracting html
			{
				test: /\.html$/,
				loader: 'raw-loader',
				exclude: /node_modules/
			},
			// Extracting postcss
			{
				test: /\.css$/,
				loader: 'style-loader!css-loader!postcss-loader',
				exclude: /node_modules/
			}
		],
		postLoaders: [
			{
				test: /\.js$/,
				loader: 'istanbul-instrumenter-loader',
				exclude: /node_modules/
			}
		]
	},
	// Setting up postcss
	postcss: function(webpack) {
		return [
			// Requiring postcss plugins
			postcssImport({
				addDependencyTo: webpack
			}),
			cssnext,
			pMixins,
			hexToRgba,
			opacityFix,
			remToPx,
			simpleVars,
			conditionalIf,
			conditionalFor,
			conditionalEach,
			nested,
			customProperties,
			mqPacker,
			zIndex,
			clearfix,
			easings,
			focus,
			removeComments,
			fontPath,
			cssStats(
				function(stats) {
					// console.log(stats);
				}
			)
		]
	},
	// Configuring cssnext options
	cssnext: {
		browsers: [
			'last 4 versions'
		],
		compress: true,
		messages: {
			console: true
		},
		sourcemap: true,
		import: {
			plugins: [
				cssReport
			]
		}
	},
	eslint: {
		configFile: '/.eslintrc'
	}
}

// Building production app in /dist folder
if (process.env.NODE_ENV === 'production') {
	// Setting dist folder path
	config.output.path = __dirname + '/dist';

	// Uglify js files
	config.plugins.push(new webpack.optimize.UglifyJsPlugin({
		compress: {
			warnings: false
		}
	}));

	// Adding sourcemaps
	config.devtool = 'source-map';
}

// Exporting webpack configuration
module.exports = config;

```

**Comment by ai** [comment]
`cssnext-loader` is not a PostCSS plugin. `cssnext-loader` is a loader for webpack with PostCSS and `cssnext-postcss` plugin inside. So you can’t set `cssnext-loader` as PostCSS plugin. You need to replace `cssnext-loader` to `postcss-cssnext` (do not forget to install it by `npm`).

**Comment by Galvo87** [comment]
Ok, now I get it.
Replaced cssnext-loader with postcss-cssnext, imports are working, but mixins aren't...

```
ERROR in ./~/css-loader!./~/postcss-loader!./app/directives/lg-hello.css
Module build failed: CssSyntaxError: /css-loader!/Volumes/My World/Development/Projects/webpack-angular/node_modules/postcss-loader/index.js!/Volumes/My World/Development/Projects/webpack-angular/app/directives/lg-hello.css:16:6: Unknown word
    at Input.error (/Volumes/My World/Development/Projects/webpack-angular/node_modules/css-loader/node_modules/postcss/lib/input.js:61:21)
    at Parser.unknownWord (/Volumes/My World/Development/Projects/webpack-angular/node_modules/css-loader/node_modules/postcss/lib/parser.js:479:26)
    at Parser.word (/Volumes/My World/Development/Projects/webpack-angular/node_modules/css-loader/node_modules/postcss/lib/parser.js:174:14)
    at Parser.loop (/Volumes/My World/Development/Projects/webpack-angular/node_modules/css-loader/node_modules/postcss/lib/parser.js:60:26)
    at parse (/Volumes/My World/Development/Projects/webpack-angular/node_modules/css-loader/node_modules/postcss/lib/parse.js:25:12)
    at new LazyResult (/Volumes/My World/Development/Projects/webpack-angular/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:57:24)
    at Processor.process (/Volumes/My World/Development/Projects/webpack-angular/node_modules/css-loader/node_modules/postcss/lib/processor.js:36:16)
    at processCss (/Volumes/My World/Development/Projects/webpack-angular/node_modules/css-loader/lib/processCss.js:171:11)
    at Object.module.exports (/Volumes/My World/Development/Projects/webpack-angular/node_modules/css-loader/lib/loader.js:24:2)
 @ ./app/directives/lg-hello.css 4:14-127
```

**Comment by ai** [comment]
Can you show `lg-hello.css`?

**Comment by Galvo87** [comment]
Sure, https://gist.github.com/Galvo87/83c6db9de06e54d3c9db

**Comment by ai** [comment]
And `button` mixin.

**Comment by Galvo87** [comment]
I just updated the previous gist ;)

**Comment by ai** [comment]
Problem is that `width` contain function, which is prohibited.

**Comment by ai** [comment]
Mixin short return object with final CSS

**Comment by Galvo87** [comment]
Ok thanks, btw I'm a newbie in js... how can I implement conditionals while not using a function?

**Comment by ai** [comment]
@Galvo87 

```
var style = {
    'background-color': 'red',
    'border': '2px solid black',
    'padding': '5px 10px'
}
if ( X ) {
    style.width = '100px';
}
return style;
```

**Comment by Galvo87** [comment]
That's strange... I already tried to write it that way but it still shows an error..

```
ERROR in ./~/css-loader!./~/postcss-loader!./app/directives/lg-hello.css
Module build failed: RangeError: Maximum call stack size exceeded
    at Rule.get (/Volumes/My World/Development/Projects/webpack-angular/node_modules/postcss-mixins/node_modules/postcss/lib/container.js:520:30)
    at Rule.append (/Volumes/My World/Development/Projects/webpack-angular/node_modules/postcss-mixins/node_modules/postcss/lib/container.js:188:51)
    at objectToNodes (/Volumes/My World/Development/Projects/webpack-angular/node_modules/postcss-mixins/index.js:31:18)
    at objectToNodes (/Volumes/My World/Development/Projects/webpack-angular/node_modules/postcss-mixins/index.js:24:46)
    at objectToNodes (/Volumes/My World/Development/Projects/webpack-angular/node_modules/postcss-mixins/index.js:24:46)
    at objectToNodes (/Volumes/My World/Development/Projects/webpack-angular/node_modules/postcss-mixins/index.js:24:46)
    at objectToNodes (/Volumes/My World/Development/Projects/webpack-angular/node_modules/postcss-mixins/index.js:24:46)
    at objectToNodes (/Volumes/My World/Development/Projects/webpack-angular/node_modules/postcss-mixins/index.js:24:46)
    at objectToNodes (/Volumes/My World/Development/Projects/webpack-angular/node_modules/postcss-mixins/index.js:24:46)
    at objectToNodes (/Volumes/My World/Development/Projects/webpack-angular/node_modules/postcss-mixins/index.js:24:46)
 @ ./app/directives/lg-hello.css 4:14-127
```

```javascript
module.exports = {
	button: function(size) {
		var styledButton = {
			'background-color': size,
			'border': '2px solid black',
			'padding': '5px 10px'
		};

		if (size == 'small') {
			button.width = '99px';
		} else if (size == 'medium') {
			button.width = '166px'
		} else if (size == 'big') {
			button.width = '222px'
		}

		return styledButton;
	}
}

```

**Comment by ai** [comment]
Look, you use `button`, instead `styledButton`.

**Comment by Galvo87** [comment]
Sorry, my fault, I only pasted the wrong code... it shows the same error with the correct variable..

**Comment by ai** [comment]
The problem is that you have a endless recursion somewhere.

If you are not familiar with JS, maybe it is not a best way. Try to write simple CSS mixin (this example mixin ) is very simple.
