### ISSUE TITLE
'mixinsDir' option issue

### ISSUE THREAD

**Issue by Galvo87** [postcss/postcss-mixins#39]
I'm building js/css bundle via webpack, with postcss-loader and postcss-mixins, writing mixins directly in js.
Everything is fine if I use this syntax, with 'mixins' option
```javascript 
postcss([ require('postcss-mixins')({ mixins: { … } }) ])
```
the mixin is found and compiled to css, and if I debug the 'mixins' value I correctly get an Obj
```javascript
"clearfix": {
	"mixin": {
		"background-color": "red",
		"&::after": {
			"content": "\"\"",
			"display": "table",
			"clear": "both"
		}
	}
}
```

Now, I want to put all my .js mixins in a separate folder, but as soon as I switch to the 'mixinsDir' option with this syntax

```javascript
require('postcss-mixins')({
    mixinsDir: path.join(__dirname, 'mixins')
})
```

and if I debug the 'mixins' value I get this:
```javascript
mixins: {
	"clearfix": {
		"clearfix": {
			"background-color": "red",
			"text-decoration": "underline",
			"&::after": {
				"content": "\"\"",
				"display": "table",
				"clear": "both"
			}
		}
	}
}
````

I get this error
```
ERROR in ./~/css-loader?sourceMap!./~/postcss-loader!./app/login/assets/main.css
Module build failed: TypeError: Cannot read property 'name' of undefined
    at insertMixin (/lessboiler2/node_modules/postcss-mixins/index.js:72:22)
    at discoverMixins (/lessboiler2/node_modules/postcss-mixins/index.js:170:17)
    at /lessboiler2/node_modules/postcss-loader/node_modules/postcss/lib/container.js:139:34
    at /lessboiler2/node_modules/postcss-import/node_modules/postcss/lib/container.js:71:26
    at Rule.each (/lessboiler2/node_modules/postcss-import/node_modules/postcss/lib/container.js:58:22)
    at Rule.walk (/lessboiler2/node_modules/postcss-import/node_modules/postcss/lib/container.js:70:21)
    at /lessboiler2/node_modules/postcss-loader/node_modules/postcss/lib/container.js:74:32
    at Root.each (/lessboiler2/node_modules/postcss-loader/node_modules/postcss/lib/container.js:58:22)
    at Root.walk (/lessboiler2/node_modules/postcss-loader/node_modules/postcss/lib/container.js:70:21)
    at Root.walkAtRules (/lessboiler2/node_modules/postcss-loader/node_modules/postcss/lib/container.js:137:25)
 @ ./app/login/assets/main.css 4:14-139 13:2-17:4 14:20-145
```

What am I doing wrong?

**Comment by TrySound** [comment]
@Galvo87 Show your js with mixin

**Comment by Galvo87** [comment]
Sure!

```javascript
module.exports = {
	clearfix: {
		'background-color': 'red',
		'text-decoration': 'underline',

		'&::after': {
			content: '""',
			display: 'table',
			clear: 'both'
		}
	}
};
```

**Comment by TrySound** [comment]
@Galvo87 Files should contain only chucks. I mean mixin per file. The name is base name of mixin js. Try to remove nesting.

**Comment by TrySound** [comment]
If this doesn't work prepare example without webpack which reproduce the problem please

**Comment by ai** [comment]
Try to replace JS mixins to JS functions:

```js
module.exports = function () {
    return {
        'background-color': 'red',
        'text-decoration': 'underline',

        '&::after': {
            content: '""',
            display: 'table',
            clear: 'both'
        }
    };
};
```

**Comment by Galvo87** [comment]
@ai if I export a function from my mixin I get this error

```javascript
ERROR in ./~/css-loader?sourceMap!./~/postcss-loader!./app/login/assets/main.css
postcss-mixins: lessboiler2/app/login/assets/custom.css:8:2: Undefined mixin clearfix

	@mixin clearfix;
 ^
}

ERROR in ./~/css-loader?sourceMap!./~/postcss-loader!./app/login/assets/main.css
Module build failed: TypeError: Cannot read property 'toString' of undefined
    at new Input (lessboiler2/node_modules/css-loader/node_modules/postcss/lib/input.js:31:23)
    at parse (lessboiler2/node_modules/css-loader/node_modules/postcss/lib/parse.js:21:17)
    at new LazyResult (lessboiler2/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:57:24)
    at Processor.process (lessboiler2/node_modules/css-loader/node_modules/postcss/lib/processor.js:36:16)
    at processCss (lessboiler2/node_modules/css-loader/lib/processCss.js:171:11)
    at Object.module.exports (lessboiler2/node_modules/css-loader/lib/loader.js:24:2)
 @ ./app/login/assets/main.css 4:14-139 13:2-17:4 14:20-145
```

**Comment by ai** [comment]
You should use mixin name in JS file name. Like `clearfix.js`.

**Comment by Galvo87** [comment]
Thanks @ai, now it works if I don't use conditionals inside the mixin... if I try to run this code

```javascript
module.exports = function(size) {
	var ciccio = '111px';

	if (size == 'big') {
		ciccio = '666px';
	}

	return {
		'background-color': 'red',
		'text-decoration': 'underline',
		'width': ciccio
	};
};
```

I get this error... am I calling the mixin's parameter improperly?

```javascript

ERROR in ./~/css-loader?sourceMap!./~/postcss-loader!./app/login/assets/main.css
postcss-mixins: lessboiler2/app/login/assets/custom.css:7:2: Undefined mixin clearfix(big)
.btn {
	@mixin clearfix(big);
 ^
}

ERROR in ./~/css-loader?sourceMap!./~/postcss-loader!./app/login/assets/main.css
Module build failed: TypeError: Cannot read property 'toString' of undefined
    at new Input (lessboiler2/node_modules/css-loader/node_modules/postcss/lib/input.js:31:23)
    at parse (lessboiler2/node_modules/css-loader/node_modules/postcss/lib/parse.js:21:17)
    at new LazyResult (lessboiler2/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:57:24)
    at Processor.process (lessboiler2/node_modules/css-loader/node_modules/postcss/lib/processor.js:36:16)
    at processCss (lessboiler2/node_modules/css-loader/lib/processCss.js:171:11)
    at Object.module.exports (lessboiler2/node_modules/css-loader/lib/loader.js:24:2)
 @ ./app/login/assets/main.css 4:14-139 13:2-17:4 14:20-145

```

**Comment by ai** [comment]
@Galvo87 sorry, have no idea. I can help you with JS debuging only after dotCSS.
